### ISSUE TITLE
Refactor categories code

### ISSUE THREAD

**Issue by Berger101** [Berger101/Muay-Thai-Club-Website#18]
As an **developer**, I want to **refactor my categories code make it more automatic**.

**Acceptance Criteria:**

- [ ] Make categories code more automatic
- [ ] Update TrainingSession class model
- [ ] Activities to categories.objects.all
- [ ] Update Category class model to work with categories page

#17
